FROM centos:7

LABEL maintainer="wuhaishui <wuhaishui@zwehs.com>"


# 修改时区
RUN ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 安装所需的工具

RUN yum update -y && \
    yum install -y wget curl git&& \
    yum install -y yum-utils

# 解决 Public key for *.rpm is not installed问题
RUN cd /etc/pki/rpm-gpg && \
    wget http://mirrors.163.com/centos/RPM-GPG-KEY-CentOS-7 && \
    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

# 添加php安装所需要的yum源
RUN wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    wget https://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    rpm -Uvh remi-release-7.rpm epel-release-latest-7.noarch.rpm && \
    yum update -y

# 设置php版本
RUN yum-config-manager --enable remi-php71
    
# 安装php
RUN yum install -y php-cli php-fpm php-mcrypt php-mysqlnd php-gd mod_php php-pdo \
    php-pear php-xml php-xmlrpc php-mbstring php-pecl-igbinary php-opcache \
    php-pecl-redis php-bcmath php-process
    
# 检查php安装
RUN php -v | head -n 1 | grep -q "PHP"

# 全局安装composer
RUN curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer
    
# composer中国镜像
RUN composer config -g repo.packagist composer https://packagist.phpcomposer.com

# php.ini
COPY php.ini /tmp/php.ini
COPY opcache.ini /tmp/opcache.ini
COPY mysql.ini /tmp/mysql.ini

RUN cp -f /tmp/php.ini /etc/php.ini && \
    cp -f /tmp/opcache.ini /etc/php.d/opcache.ini && \
    cp -f /tmp/mysql.ini /etc/php.d/mysql.ini && \
    rm -f /tmp/*.ini

# SSH
COPY insecure_id_rsa /tmp/id_rsa
COPY insecure_id_rsa.pub /tmp/id_rsa.pub

RUN if [ ! -d /root/.ssh ]; then \
    mkdir -p /root/.ssh \
;fi

RUN cat /tmp/id_rsa.pub >> /root/.ssh/authorized_keys \
    && cat /tmp/id_rsa.pub >> /root/.ssh/id_rsa.pub \
    && cat /tmp/id_rsa >> /root/.ssh/id_rsa \
    && rm -f /tmp/id_rsa* \
    && chmod 644 /root/.ssh/authorized_keys /root/.ssh/id_rsa.pub \
    && chmod 400 /root/.ssh/id_rsa

# 清理战场
RUN yum clean all && \
    rm -rf /var/cache/yum/*

RUN mkdir -p /run/php-fpm

WORKDIR /var/www/example

CMD [ "php-fpm" ]

EXPOSE 9000 22
